---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Set user defaults
  ansible.builtin.user:
    name: "{{ username }}"
    generate_ssh_key: true
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519
    ssh_key_comment: "{{ username }}@{{ hostname }}"
    shell: /usr/bin/zsh
